### ISSUE TITLE
services tienen codigo q deberian ir en las entidades

### ISSUE THREAD

**Issue by maurociancio** [S2JuanS2/TP-Desarrollo-con-Nuevas-Tecnologias#11]
@Transactional
    def agregarArticuloACesta(long articuloId, long clienteId) {
        Cliente cliente = Cliente.get(clienteId)
        Articulo articulo = Articulo.get(articuloId)

        cliente.cesta.cantidadDeArticulos++
        articulo.stock--
        cliente.cesta.montoTotal += articulo.precio
        cliente.cesta.articulos.add(articulo)
        cliente.cesta.save(flush: true)
    }

esto:
        cliente.cesta.cantidadDeArticulos++
        articulo.stock--
        cliente.cesta.montoTotal += articulo.precio
        cliente.cesta.articulos.add(articulo)
        cliente.cesta.save(flush: true)

deberia estar en un metodo o varios de entidades.
otra vez aparece el flush, revisar xq es necesario ?

**Comment by maurociancio** [comment]
cliente.cesta.cantidadDeArticulos--
        articulo.stock++
        cliente.cesta.montoTotal -= articulo.precio
        cliente.cesta.articulos.remove(articulo)
        cliente.cesta.save(flush: true)

idem

**Comment by maurociancio** [comment]
@Transactional
    def vaciarCestaDePedidoFinalizado(long clienteId){
        Cliente cliente = Cliente.get(clienteId)
        Cesta cesta = cliente.cesta
        Articulo articuloEnStock
        cesta.articulos.each{ articulo ->
            articuloEnStock = Articulo.get(articulo.id)
            cesta.cantidadDeArticulos--
            cesta.montoTotal -= articuloEnStock.precio
        }
        cliente.cesta.articulos.clear()
        cliente.cesta.save(flush: true)
    }


idem, mucho codigo acá

**Comment by claram97** [comment]
Cuando armamos métodos en las entidades y los llamamos desde el service correspondiente, no se actualiza correctamente, por eso es que lo resolvimos así. Alguna idea de por qué puede estar pasando esto?

**Comment by maurociancio** [comment]
Fíjate de usar setters en ves de atributo
Ejemplo
Entidad.atributo = algo
Usar
Entidad.setAtributo(algo)
