### ISSUE TITLE
esto tiene q ir en la entidad

### ISSUE THREAD

**Issue by maurociancio** [S2JuanS2/TP-Desarrollo-con-Nuevas-Tecnologias#14]
def confirmarPedido(long pedidoId){
        Pedido pedido = Pedido.get(pedidoId)
        if(pedido.enPreparacion()){
            pedido.estado = EstadoPedido.LISTO_PARA_ENTREGAR
        }else if(pedido.enConfirmacion()){
            pedido.estado = EstadoPedido.EN_PREPARACION
        }else if(pedido.listoParaEntregar()){
            pedido.estado = EstadoPedido.ENTREGADO
            pedido.cliente.calificacionesPendientes++
        }
        pedido.save(flush: true)
    }

**Comment by maurociancio** [comment]
es un poco turbio q el metodo confirmarPedido transicione de estado al próximo.... me imagino que puede dar a confusion

tenes la vista cargada, supones q el proximo estado es EN_PREPARACION xq actualmente estas en LISTO_PARA_ENTREGAR
alguien en otro browser llama a este metodo, entonces transiciona a EN_PREPARACION
vos clickas en tu browswer desactualizado y ahora el estado final es ENTREGADO y no te das cuenta....

se entiende?

**Comment by S2JuanS2** [comment]
Creo entender el problema, pero si pudiera explayarse un poco mas con algún centro se lo agradecería

**Comment by maurociancio** [comment]
Podrías hacer varios action q cada uno indique a estado queres ir.

Tipo cambiarAEnPreparacion sea un método de un controller y si no puede ir
a ese estado falle.

Así con todos los estados
