### ISSUE TITLE
xq esto no esta en un service?

### ISSUE THREAD

**Issue by maurociancio** [S2JuanS2/TP-Desarrollo-con-Nuevas-Tecnologias#2]
def aumentarStock(){

        Articulo.withTransaction{ 
            Articulo articulo = Articulo.get(params.articulo)
            if(!articulo){
                throw new ObjetoNoExisteException("El articulo no existe")
            }
            articulo.stock++
            articulo.save(flush: true)
        }
        redirect(controller: "administrador", action: "vistaAdministrador")
    }

**Comment by S2JuanS2** [comment]
Buenas profe!, tengo una duda, cuando yo hago articulo.sumarStock() esa actualización no estaría persistiendo en la base de datos pero si uso directamente el stock++ si persiste, y cuando llamo a ambos, al metodo y al atributo directamente, en la base de datos se suma dos veces. Mi duda es porque cuando llamo solo al metodo, no persiste?

**Comment by maurociancio** [comment]
Fíjate el otro comentario q deje  .
No usen entidad.atributo = algo sino entidad.setAtributo(algo)

**Comment by S2JuanS2** [comment]
perfecto gracias
